on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
#  build:
#    runs-on: ubuntu-latest
#    timeout-minutes: 15
#
#    env:
#      DOTNET_NOLOGO: true
#      DOTNET_CLI_TELEMETRY_OPTOUT: true
#
#    strategy:
#      matrix:
#        include:
#          - category: menu
#            cmd: --filter TestCategory=Menu
#          - category: cooking
#            cmd: --filter TestCategory=Cooking
#            
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: 9.0.x
#          source-url: ${{ secrets.NUGET_SOURCE }}
#        env:
#          NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
#
#      - name: Build
#        run: dotnet build --configuration Release
#
#      - name: Test
#        run: dotnet test ${{ matrix.cmd }} --configuration Release --no-build
        
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
#    needs: "build"
    
    steps:
      - name: Download swagger-coverage
        run: |
          wget https://github.com/viclovsky/swagger-coverage/releases/download/1.5.0/swagger-coverage-1.5.0.zip
          unzip swagger-coverage-1.5.0.zip