on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      matrix:
        include:
          - category: menu
            cmd: --filter TestCategory=Menu
          - category: cooking
            cmd: --filter TestCategory=Cooking

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          source-url: ${{ secrets.NUGET_SOURCE }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test ${{ matrix.cmd }} --configuration Release --no-build

      - name: Copy actual json
        run: cp ./FoodApi.Tests/swagger.json ./FoodApi.Tests/bin/generated_specs/swagger.json

      - name: Upload openapi coverage results
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1d
          name: openapi-coverage-output-${{ matrix.category }}
          path: ./FoodApi.Tests/bin/generated_specs/*.json
        
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: "build"
    
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: openapi-coverage-output
          pattern: openapi-coverage-output-*
          merge-multiple: true
      
#      - name: Download All Artifacts
#        uses: actions/download-artifact@v4
#        with:
#          name: openapi-coverage-resources
  
      - run: ls -R openapi-coverage-output

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          failOnError: false
          name: openapi-coverage-*

#      - name: Restore cache
#        id: cache-coverage-restore
#        uses: actions/cache/restore@v4
#        with:
#          path: swagger-coverage-commandline
#          key: swagger-coverage-commandline

      - name: Cache coverage tool
        id: cache-coverage
        uses: actions/cache@v4
        with:
          path: ./swagger-coverage-commandline
          key: swagger-coverage-commandline

      - name: Download swagger-coverage
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/viclovsky/swagger-coverage/releases/download/1.5.0/swagger-coverage-1.5.0.zip
          unzip swagger-coverage-1.5.0.zip
          mv swagger-coverage-commandline-1.5.0 swagger-coverage-commandline

#      - name: Save cache
#        if: steps.cache-coverage-restore.outputs.cache-hit != 'true'
#        uses: actions/cache/save@v4
#        with:
#          path: swagger-coverage-commandline
#          key: swagger-coverage-commandline
      
      - run: ls -R swagger-coverage-commandline      
      
#      - name: Copy all file to folder
#        run: cp -R ./openapi-coverage ./swagger-coverage-commandline/

      - run: mv ./openapi-coverage-output/swagger.json ./
      - run: mv ./build/openapi-coverage ./

      - name: Run coverage tool
        run: |
          ./swagger-coverage-commandline/bin/swagger-coverage-commandline -q \
          -s ./swagger.json \
          -i ./openapi-coverage-output \
          -c ./openapi-coverage/config.minimal.json

      - name: Run coverage tool
        run: |
          ./swagger-coverage-commandline/bin/swagger-coverage-commandline -q \
          -s ./swagger.json \
          -i ./openapi-coverage-output \
          -c ./openapi-coverage/config.default.json
          
      - run: ls -R ./
        
#      - name: Convert HTML to Markdown
#        id: html2markdown
#        uses: rknj/html2markdown@v1.1.0
#        with:
#          html-file: "swagger-coverage-report.html"
      - uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - run: npm install turndown@7.2.0 turndown-plugin-gfm@1.0.2

      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            var TurndownService = require('turndown')
            var turndownPluginGfm = require('turndown-plugin-gfm')

            var gfm = turndownPluginGfm.gfm
            var turndownService = new TurndownService()
            turndownService.use(gfm)

            const fileName = 'report';
            const html = fs.readFileSync(fileName + ".html", "utf8");
            var markdown = turndownService.turndown(html)
            fs.writeFileSync("swagger-coverage-report.md", markdown);
            
            const summary = core.summary;
  
              core.summary.addRaw('Some content here :speech_balloon:', true)
            // Output: Some content here :speech_balloon:\n
              
              // Add an operating system-specific end-of-line marker
              core.summary.addEOL()
            // Output (POSIX): \n
            // Output (Windows): \r\n
              
              // Add a codeblock with an optional language for syntax highlighting
              core.summary.addCodeBlock('console.log(\'hello world\')', 'javascript')
            // Output: <pre lang="javascript"><code>console.log('hello world')</code></pre>
              
              // Add a list, second parameter indicates if list is ordered, defaults to false
              core.summary.addList(['item1','item2','item3'], true)
            // Output: <ol><li>item1</li><li>item2</li><li>item3</li></ol>
              
              // Add a collapsible HTML details element
              core.summary.addDetails('Label', 'Some detail that will be collapsed')
            // Output: <details><summary>Label</summary>Some detail that will be collapsed</details>
              
              // Add an image, image options parameter is optional, you can supply one of or both width and height in pixels
            core.summary.addImage('example.png', 'alt description of img', {width: '100', height: '100'})
            // Output: <img src="example.png" alt="alt description of img" width="100" height="100">
              
              // Add an HTML section heading element, optionally pass a level that translates to 'hX' ie. h2. Defaults to h1
              core.summary.addHeading('My Heading', '2')
            // Output: <h2>My Heading</h2>
              
              // Add an HTML thematic break <hr>
              core.summary.addSeparator()
            // Output: <hr>
              
              // Add an HTML line break <br>
              core.summary.addBreak()
            // Output: <br>
              
              // Add an HTML blockquote with an optional citation
              core.summary.addQuote('To be or not to be', 'Shakespeare')
            // Output: <blockquote cite="Shakespeare">To be or not to be</blockquote>
              
              // Add an HTML anchor tag
              core.summary.addLink('click here', 'https://github.com')
            // Output: <a href="https://github.com">click here</a>
            const tableData = [
            {data: 'Header1', header: true},
            {data: 'Header2', header: true},
            {data: 'Header3', header: true},
            {data: 'MyData1'},
            {data: 'MyData2'},
            {data: 'MyData3'}]
            
            core.summary.addTable([tableData])
            await summary.write();
            
      - run: cat report.html >> $GITHUB_STEP_SUMMARY
      - run: cat swagger-coverage-report.md >> $GITHUB_STEP_SUMMARY
        
#      - name: Add image tag to comments
#        uses: actions/github-script@v7
#        continue-on-error: true
#        if: ${{ github.event_name == 'pull_request' }}
#        with:
#          github-token: ${{github.token}}
#          script: |
#            github.rest.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: 'Last build image tag `${{ needs.prepare.outputs.image_tag }}`'
#            })