on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      matrix:
        include:
          - category: menu
            cmd: --filter TestCategory=Menu
          - category: cooking
            cmd: --filter TestCategory=Cooking
            
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          source-url: ${{ secrets.NUGET_SOURCE }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test {{ matrix.cmd }} --configuration Release --no-build
