on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      matrix:
        include:
          - category: menu
            cmd: --filter TestCategory=Menu
          - category: cooking
            cmd: --filter TestCategory=Cooking
          - category: other
            cmd: --filter TestCategory=Other
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          source-url: ${{ secrets.NUGET_SOURCE }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        env:
          ENABLE_SWAGGER_COVERAGE: true
        run: dotnet test ${{ matrix.cmd }} --configuration Release --no-build

      - name: Upload openapi coverage results
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1d
          name: openapi-coverage-output-${{ matrix.category }}
          path: ./FoodApi.Tests/bin/generated_specs/*.json

  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: "build"
    env:
      KUSTO_DEV_URI: ${{ vars.KUSTO_DEV_URI }}
      KUSTO_AAD_AUTHORITY_ID: ${{ secrets.KUSTO_AAD_AUTHORITY_ID}}
      KUSTO_AAD_APP_ID: ${{ secrets.KUSTO_AAD_APP_ID }}
      KUSTO_APP_KEY: ${{ secrets.KUSTO_APP_KEY }}

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: openapi-coverage-output
          pattern: openapi-coverage-output-*
          merge-multiple: true

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          failOnError: false
          name: openapi-coverage-*
 
      - name: Copy templates
        shell: bash
        run: |
          mkdir -p jsons
          cp openapi-coverage-output/swagger.json jsons/lf.json
          cp openapi-coverage-output/swagger.json jsons/sm.json

      - uses: alekskulakov/ci.actions.swaggercoverage@99300d0cc6955e6a2d286c7f205711f88d0a340b
        with:
          spec-path: 'jsons/lf.json'
          input-path: 'openapi-coverage-output'
          use-minimal-config: false
          use-full-config: 'true'
          throw-on-fail: false
          skip-send-to-kusto: true
          
      - uses: alekskulakov/ci.actions.swaggercoverage@c0181a68d0bf62c07aeb6082ff3b3db1addf2115
        with:
          spec-path: 'jsons/sm.json'
          input-path: 'openapi-coverage-output'
          use-minimal-config: false
          use-full-config: 'true'
          throw-on-fail: false
          skip-send-to-kusto: true