on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      matrix:
        include:
          - category: menu
            cmd: --filter TestCategory=Menu
          - category: cooking
            cmd: --filter TestCategory=Cooking
          - category: other
            cmd: --filter TestCategory=Other
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          source-url: ${{ secrets.NUGET_SOURCE }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        env:
          ENABLE_SWAGGER_COVERAGE: true
        run: dotnet test ${{ matrix.cmd }} --configuration Release --no-build

      - name: Upload openapi coverage results
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1d
          name: openapi-coverage-output-${{ matrix.category }}
          path: ./FoodApi.Tests/bin/generated_specs/*.json

  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: "build"

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: openapi-coverage-output
          pattern: openapi-coverage-output-*
          merge-multiple: true

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          failOnError: false
          name: openapi-coverage-*

      - run: mv ./openapi-coverage-output/swagger.json ./
        continue-on-error: true

      - uses: alekskulakov/ci.actions.swaggercoverage@00f009500fb6dd4933481a4599ae132c38c2d6ed
        with:
          spec-path: 'swagger.json'
          input-path: 'openapi-coverage-output'
          throw-on-fail: ${{ vars.COVERAGE_THROW_ON_FAIL }}